from django.conf.urls import include, patterns, url
from mirrors import views

COMPONENT_RE = '^component/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[-\w]+)'

urlpatterns = patterns(
    'mirrors.views',
    url(r'^component$',
        views.ComponentList.as_view(),
        name='component-list'),
    url(r"{}$".format(COMPONENT_RE),
        views.ComponentDetail.as_view(),
        name='component-detail'),
    url(r"{}/attribute$".format(COMPONENT_RE),
        views.ComponentAttributeList.as_view(),
        name='component-attribute-list'),
    url(r"{}/attribute/(?P<name>[-\w_]+)$".format(COMPONENT_RE),
        views.ComponentAttributeDetail.as_view(),
        name='component-attribute-detail'),
    url(r"{}/data$".format(COMPONENT_RE),
        views.ComponentData.as_view(),
        name='component-data'),
    url(r"{}/lock$".format(COMPONENT_RE),
        views.ComponentLock.as_view(),
        name='component-lock'),
    url(r"{}/revision$".format(COMPONENT_RE),
        views.ComponentRevisionList.as_view(),
        name='component-revision-list'),
    url(r"{}/valid$".format(COMPONENT_RE),
        views.ComponentValidity.as_view(),
        name='component-validity'),
    url(r"{}/revision/(?P<version>[\d]+)$".format(COMPONENT_RE),
        views.ComponentRevisionDetail.as_view(),
        name='component-revision-detail'),
    url(r"{}/revision/(?P<version>[\d]+)/data$".format(COMPONENT_RE),
        views.ComponentRevisionData.as_view(),
        name='component-revision-data'),
    url(r'^schemas$',
        views.component_schemas,
        name='component-schemas'),
    url(r'api-auth/', include('rest_framework.urls',
                              namespace='rest_framework')),
)
