from django.conf.urls import patterns, url
from mirrors import views

urlpatterns = patterns(
    'mirrors.views',
    url(r'^component$',
        views.ComponentList.as_view(),
        name='component-list'),
    url(r'^component/(?P<slug>[-\w]+)$',
        views.ComponentDetail.as_view(),
        name='component-detail'),
    url(r'^component/(?P<slug>[-\w]+)/attribute$',
        views.ComponentAttributeList.as_view(),
        name='component-attribute-list'),
    url(r'^component/(?P<slug>[-\w]+)/attribute/(?P<name>[-\w_]+)$',
        views.ComponentAttributeDetail.as_view(),
        name='component-attribute-detail'),
    url(r'^component/(?P<slug>[-\w]+)/data$',
        views.ComponentData.as_view(),
        name='component-data'),
    url(r'^component/(?P<slug>[-\w]+)/lock$',
        views.ComponentLock.as_view(),
        name='component-lock'),
    url(r'^component/(?P<slug>[-\w]+)/revision$',
        views.ComponentRevisionList.as_view(),
        name='component-revision-list'),
    url(r'^component/(?P<slug>[-\w]+)/revision/(?P<version>[\d]+)$',
        views.ComponentRevisionDetail.as_view(),
        name='component-revision-detail'),
    url(r'^component/(?P<slug>[-\w]+)/revision/(?P<version>[\d]+)/data$',
        views.ComponentRevisionData.as_view(),
        name='component-revision-data'),
    url(r'^schemas$',
        views.component_schemas,
        name='component-schemas')
)
# url(r'^component/(?P<slug>[-\w]+)/attribute/(?P<attr_name>[-\w_]+)/(?P<index>[\d]+)$',
#     views.ComponentAttributeDetail.as_view(),
#     name='component-attribute-detail'),
